# Original package name lgi
%define oname lgi
%define oversion 0.6.2-1
%define rockspec ../rocks/lgi.rockspec
Name: lua-module-%oname
Version: 0.6.2
Release: alt1_lr1
Summary: Lua bindings to GObject libraries
License: MIT/X11
Group: Development/Other
Url: http://github.com/pavouk/lgi
Provides: luarocks(%oname) = %version

# git://github.com/pavouk/lgi.git
Source: %oname.tar
Source1: http://luarocks.org/repositories/rocks/lgi.rockspec
#lgi-0.6.2-1.rockspec

#TODO Requires
BuildPreReq: rpm-macros-lua
# Automatically added by buildreq on Tue Jul 03 2012 (-bi)
# optimized out: elfutils glib2-devel gobject-introspection libffi-devel lua5 pkg-config python-base python-module-distribute
BuildRequires: gobject-introspection-devel liblua5-devel luarocks

%description
Dynamic Lua binding to any library which is introspectable
using gobject-introspection.  Allows using GObject-based libraries
directly from Lua.

%prep
%setup -n %oname-%version

%install
mkdir -p %buildroot%luarocks_dbdir
cp -a %luarocks_dbdir/manifest %buildroot%luarocks_dbdir ||:
cp -a %SOURCE1 %oname-%oversion.rockspec
luarocks make --to=%buildroot%prefix %oname-%oversion.rockspec
rm -rf docs
mv %buildroot%luarocks_dbdir/%oname/%oversion/docs docs
ln -s %_docdir/%name-%version %buildroot%luarocks_dbdir/%oname/%oversion/docs

%files
%lua_modulesdir/*
%lua_modulesdir_noarch/*
%luarocks_dbdir/%oname
%doc README* docs/*
%exclude %luarocks_dbdir/manifest

%changelog
* Tue Jul 03 2012 Ildar Mulyukov <ildar@altlinux.ru> 0.6.2-alt1_lr1
- autogenerated by lrimport
