#! /usr/bin/env python

def build(bld):
    bld.shlib(
        source = 'core.c callable.c marshal.c glib.c compound.c',
        target = 'lgi',
        uselib = ['LUA', 'GI'],
        install_path = '${LUA_INSTALL_CMOD}',
        )
    bld.install_files('${LUA_INSTALL_LMOD}/', 'lgi.lua')
